#181339524-docker-setup-for-cabal-project
atlp-rwanda/cabal-bn-be pull request #14
Opened 2022-03-04 07:20 UTC by Code-250

### what does this Pull Request do?
this Pull Request sets up the docker for the project.

### description of tasks to be completed
 - dockerizing the whole project to be used in the development mode.
 - setting up docker-compose well and Dockerfile

### how should this Pull Request be tested?

 - checkout `ch-setup-docker-for-api-#181339524` branch
 - run in your terminal `docker-compose up` to start the docker containers and the project.
 - to install some packages in the terminal use `docker exec -it cabal-backend sh` to get into the project container.

### pivotal tracker
 - [docker-pivotal-tracker](https://www.pivotaltracker.com/n/projects/2555280)

### Questions
N/A

2022-03-04 14:57 UTC, ncutixavier requested changes

2022-03-04 14:57 UTC, ncutixavier commented on .env.example
> +DATABASE_URL=postgres://postgres@127.0.0.1:5432/eagles
Replace this with previous placeholder

2022-03-04 14:57 UTC, ncutixavier commented on src/app.js
> +  res.send({ status: 200, message: "Welcome to Barefoot Nomad." });
Replace with `res.status(200).json({....})` and Implement the same for other

2022-03-04 15:35 UTC, Tsa2341 approved these changes

2022-03-07 06:41 UTC, niyonkurueric approved these changes

2022-03-07 06:46 UTC, tuyizerejean approved these changes

2022-03-07 06:51 UTC, merged