#181339532-ResetPassword-via-email
atlp-rwanda/cabal-bn-be pull request #17
Opened 2022-03-10 11:05 UTC by niyonkurueric

### What does this PR do?
This PR combined all tasks about resetting passwords but all those have in swagger and tested 
### Description of Task to be completed?

- the first step for forgetting password: have a field  of putting email and checking if it has into the database and sending your email link into your email
- second step for reset password: this is used to putting new password for and give you message is well reset
- all fields of the above have been validated 
### Relevant pivotal tracker stories?
[#181339532](https://www.pivotaltracker.com/story/show/181339532)
### How can you manually test this

- git clone repository
- testing using swagger documentation 
### screenshot
![Screenshot from 2022-03-10 13-02-28](https://user-images.githubusercontent.com/76616593/157649190-41b5ecfc-b63e-43f8-a363-c8bf19cab8cb.png)

2022-03-15 15:46 UTC, Eli250 approved these changes

2022-03-16 07:45 UTC, blandri approved these changes

2022-03-16 08:11 UTC, ncutixavier requested changes

2022-03-16 08:11 UTC, ncutixavier commented on src/controllers/user.controller.js
> +                    email: 'cabalbarefoot@gmail.com',
This info needs to be in .env file

2022-03-16 08:11 UTC, ncutixavier commented on src/controllers/user.controller.js
> +            res.status(403).json({ status: 403, message: 'Email not exist' });
- Change status code for not found code
- Change message to "Email has not found"

2022-03-16 08:11 UTC, ncutixavier commented on src/controllers/user.controller.js
> +            return res.status(500).send({ message: error.message });
Provide appropriate error for the user

2022-03-16 08:11 UTC, ncutixavier commented on src/controllers/user.controller.js
> +            const token = req.params.token;
implement object destructuring

2022-03-16 08:11 UTC, ncutixavier commented on src/controllers/user.controller.js
> +            return res.status(500).send({ message: error.message });
Also, refactor your code to remain with few variables

2022-03-16 08:11 UTC, ncutixavier commented on src/documentation/forgot.doc.js
> +    '/users/forgot': {
change route to " /users/forgot-password", and implement the same on reset password route

2022-03-16 08:11 UTC, ncutixavier commented on src/documentation/forgot.doc.js
> +            ],
Format your code

2022-03-16 08:11 UTC, ncutixavier commented on src/email/index.js
> +    </html>`;
Create files in the `utils` folder and add these codes.

2022-03-16 08:11 UTC, ncutixavier commented on tests/password-reset.test.js
> +            .patch(`/api/v1/users/reset/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiaWF0IjoxNjQ3MTUzNTY4LCJleHAiOjE2NDcxNTQxNjh9.k8jHrhjRJXymilhpotQTVjhxhF4_4jziU2w1tHTh3WA`)
Reduce the length of this line

2022-03-17 08:22 UTC, ncutixavier commented
![image](https://user-images.githubusercontent.com/51375428/158766951-c77d690a-8dfa-46c2-8618-45be2b97cba3.png)

2022-03-17 08:25 UTC, ncutixavier reviewed
- You're not allowed to return user info when logged in
![image](https://user-images.githubusercontent.com/51375428/158767280-67d452b4-493d-4bfc-bc83-37197d951e25.png)

- Rephrase the message when reset is done
![image](https://user-images.githubusercontent.com/51375428/158767864-138f0cff-d726-4b65-b933-f6c6fb01a0dd.png)

2022-03-18 13:39 UTC, ncutixavier approved these changes

2022-03-18 13:43 UTC, ncutixavier approved these changes

2022-03-18 14:03 UTC, merged