#18133958 user login and authentication
atlp-rwanda/cabal-bn-be pull request #18
Opened 2022-03-10 12:15 UTC by Gabin-ishimwe

## What does this PR do?
i create a login route for a user and protected some route by adding authentication
## Description of Task to be completed?
add more test to make them 85%, there is a coverage of 80%
## How should this be manually tested?

- clone this repository
- run you server with `yarn run dev` (remember to setup you dev database)
- for testing run your server by `yarn run test` (remember to setup you test database)
- testing these routes in postman: `/api/v1/users/login`
- test this route for authentication: `/api/v1/users/testAuth`

## Any background context you want to provide?
## What are the relevant pivotal tracker stories?
[#18133958](https://www.pivotaltracker.com/n/projects/2555280/stories/181339528)
## Screenshots (if appropriate)
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/87947641/157659507-00ffd130-045a-4ec8-b771-9f8ecfa443c8.png">

## Questions:

2022-03-10 15:49 UTC, niyonkurueric approved these changes

2022-03-10 15:51 UTC, Code-250 approved these changes

2022-03-10 16:09 UTC, ncutixavier requested changes

2022-03-10 16:09 UTC, ncutixavier commented on src/controllers/user.controller.js
> +        res.status(401).send("Invalid password")
Return json, and change the status code.

2022-03-10 16:09 UTC, ncutixavier commented on src/controllers/user.controller.js
> +      res.status(404).send({error: error})
- Remove the console and add provide a meaningful message to the user
`res.status(500).send({error: error, message: ""})`
- change status code

2022-03-10 16:09 UTC, ncutixavier commented on src/middlewares/passport.middleware.js
> +// );
Remove commented code

2022-03-10 16:09 UTC, ncutixavier commented on src/middlewares/user.middleware.js
> +    res.status(401).send("Access denied")
Return json

2022-03-10 16:09 UTC, ncutixavier commented on src/routes/api/user.route.js
> +
Remove unused code

2022-03-10 16:09 UTC, ncutixavier commented on src/services/user.service.js
> +      res.status(404).send("User not found")
Return json

2022-03-10 16:42 UTC, Gabin-ishimwe commented on src/services/user.service.js
> +      res.status(404).send("User not found")
done

2022-03-10 16:42 UTC, Gabin-ishimwe commented on src/routes/api/user.route.js
> +
done

2022-03-10 16:42 UTC, Gabin-ishimwe commented on src/middlewares/user.middleware.js
> +    res.status(401).send("Access denied")
done

2022-03-10 16:43 UTC, Gabin-ishimwe commented on src/middlewares/passport.middleware.js
> +// );
done

2022-03-10 16:43 UTC, Gabin-ishimwe commented on src/controllers/user.controller.js
> +        res.status(401).send("Invalid password")
done

2022-03-10 16:59 UTC, ncutixavier commented
Please fulfill your PR Description

2022-03-10 17:10 UTC, ncutixavier reviewed
- Add a description of your task in PR Description
- Your deployment is not working

2022-03-11 08:07 UTC, ncutixavier approved these changes

2022-03-11 08:08 UTC, merged