#181339522-API-documentation-using-swagger
atlp-rwanda/cabal-bn-be pull request #2
Opened 2022-02-28 14:11 UTC by Code-250

### what does this Pull Request do?
this Pull Request sets up the documentation of the barefoot nomad project using swagger.

### description of tasks to be completed
 - setting up the documentation of the project using Swagger
 - documenting the home route using swagger to test the working of the swagger.

### how should this Pull Request be tested?
 - checkout `ch-setup-swagger-documentation-#181339522` branch
 - run in your terminal `yarn run dev` to start the project
 - run in your browser `localhost:port/api-docs` to go to the swagger doc link.

### pivotal tracker
 - [pivotal tracker link](https://www.pivotaltracker.com/n/projects/2555280)

### screeshots
<img width="1440" alt="Screen Shot 2022-02-28 at 16 08 38" src="https://user-images.githubusercontent.com/47631065/155997118-346fe6b6-863e-4554-a47e-665a2f4e2291.png">

### Questions
N/A

2022-02-28 14:35 UTC, Gabin-ishimwe approved these changes
good work richard, i liked how you documented each route and imported it in the main document(index.js). it is very neat and clear

2022-02-28 14:57 UTC, Tsa2341 approved these changes
Nice work Richard.

2022-03-03 14:59 UTC, ncutixavier requested changes

2022-03-03 14:59 UTC, ncutixavier commented on .env.example
> +BASE_URL=localhost:port
- Remove one env.example

2022-03-03 14:59 UTC, ncutixavier commented on .env.sample
> +DEV_DATABASE_URL=postgres://postgres:Richard@Munyemana@127.0.0.1:5432/cabal
Remove your credential and replace it with the previous one

2022-03-03 14:59 UTC, ncutixavier commented on src/documentation/welcome.js
> +      responses,
Add only required response not all of them

2022-03-03 14:59 UTC, ncutixavier commented on src/documentation/index.js
> +    description: "Employee Travel Management",
Change this description

2022-03-03 15:46 UTC, ncutixavier approved these changes

2022-03-03 15:47 UTC, merged