#181339530: log out functionalities
atlp-rwanda/cabal-bn-be pull request #20
Opened 2022-03-13 08:28 UTC by blandri

### What does this PR do?

this PR is for logging out functionality

### Description of Task to be completed?

- A user logs in 
- A user logs out using the access token given on log in
- A user cant use the access token when they are logged out

### How should this be manually tested?

- register on the app
- log in and take the token
- use it to logout

- remotely: go to this link: https://staging-bare-feature-18-rszml6.herokuapp.com/api-docs/#/
- locally: clone this repo
- use postman and login and get the token
         - POST    **http://localhost:3000/api/v1/user/login**
- use postman to logout
         - POST   **http://localhost:3000/api/v1/user/logout**
         

### What are the relevant pivotal tracker stories?

[#181339530](https://www.pivotaltracker.com/story/show/181339527)

### Screenshots (if appropriate)
![image](https://user-images.githubusercontent.com/95901517/158051427-ac88093e-d2d9-4ce5-a115-b1111e1c0c6f.png)

2022-03-13 19:22 UTC, Gabin-ishimwe requested changes
resolve your circle ci problem for your tests to run

2022-03-15 10:09 UTC, Eli250 requested changes
Add a new line at the end of each file.

2022-03-15 10:09 UTC, Eli250 commented on tests/user.test.js
>  });
Add new line at the end

2022-03-15 10:09 UTC, Eli250 commented on src/middlewares/authentication.js
> +};
Add a new line a the end.

2022-03-15 10:09 UTC, Eli250 commented on src/redis/index.js
> +export default client;
Add new line at the end.

2022-03-17 09:29 UTC, Code-250 approved these changes

2022-03-17 16:43 UTC, closed without merging