#181339530 loggout
atlp-rwanda/cabal-bn-be pull request #27
Opened 2022-03-18 16:15 UTC by blandri

### What does this PR do?

this PR is for logging out functionalities

### Description of Task to be completed?
 
- A user logs out using the access token given on log in
- The user's token is stored in a new model called Blacklist
- A used access token cant be used again

### How should this be manually tested?

- Clone this [repo](https://github.com/atlp-rwanda/cabal-bn-be.git)
- Download redis server on your pc if you are going to test locally

- register on the app
- log in and take the token
- use it to logout

- use postman and login and get the token
         - POST    **http://localhost:3000/api/v1/users/login**
- use postman to logout
         - POST   **http://localhost:3000/api/v1/users/logout**

- Link for swagger: waiting for deployment ..............

         

### What are the relevant pivotal tracker stories?

[#181339530](https://www.pivotaltracker.com/n/projects/2555280)

### Screenshots (if appropriate)
![image](https://user-images.githubusercontent.com/95901517/158848941-4448b4bd-4261-4b2e-9231-a38628fa3615.png)

2022-03-21 06:12 UTC, Code-250 approved these changes

2022-03-21 07:03 UTC, Tsa2341 approved these changes

2022-03-21 10:01 UTC, Eli250 approved these changes

2022-03-22 07:35 UTC, ncutixavier requested changes

2022-03-22 07:35 UTC, ncutixavier commented on src/controllers/user.controller.js
> +      return res.status(404).json({ message: 'not found' });
Change the status code and error message

2022-03-22 07:35 UTC, ncutixavier commented on src/middlewares/authentication.js
> +    res.status(401).send({ message: 'You are not logged in' });
Change the status code and error message

2022-03-23 18:21 UTC, ncutixavier approved these changes

2022-03-23 18:21 UTC, merged