#23181339538 Users should be able to like/unlike an accommodation facility
atlp-rwanda/cabal-bn-be pull request #31
Opened 2022-03-23 07:11 UTC by Tsa2341

### what does this Pull Request do?

this Pull Request implements like and unlike accommodations

### description of tasks to be completed

 - user should be able to like an accommodation
 - user should be able to unlike an accommodation

### how should this Pull Request be tested?

 - remottelly: **https://staging-bare-feature-18-lazhmv.herokuapp.com/api-docs**
 - locally: clone this repo and checkout **feature/#23181339538-like-and-unlike-accommodation**  branch
 - add all environment variables and run npm run dev after running npm run dbmigrate:all to seed data
 - checkout this api to login
 
             http://localhost:5000/api/v1/users/login

- get the token and authenticate with a bearer and then hit these APIs to test the like and unlike endpoints

           - **POST**   http://localhost:5000/api/v1/accommodations/:accommodationId/like
           - **POST**  http://localhost:5000/api/v1/accommodations/:accommodationId/unlike

### What are the relevant pivotal tracker stories?

 - [#181339538](https://www.pivotaltracker.com/story/show/181339538)

#### Screenshots (if appropriate)

![Screenshot (35)](https://user-images.githubusercontent.com/83913153/159643307-98da532b-4930-44da-a9ff-e85f33f3945f.png)

2022-03-23 08:39 UTC, blandri approved these changes

2022-03-23 08:55 UTC, Gabin-ishimwe approved these changes

2022-03-23 09:15 UTC, Code-250 commented on tests/password-reset.test.js
> +  //     .request(app)
please do not comment other peoples tests

2022-03-23 09:16 UTC, Code-250 requested changes
please do not comment other people's test

2022-03-23 14:11 UTC, Code-250 approved these changes

2022-03-24 16:59 UTC, ncutixavier commented
### Comments

- Try to raise your test coverage to be above 85%

2022-03-28 13:16 UTC, ncutixavier approved these changes

2022-03-28 13:17 UTC, merged