#181339541-trip-comment
atlp-rwanda/cabal-bn-be pull request #32
Opened 2022-03-23 14:28 UTC by Code-250

### what does this Pull Request do?
this Pull Request implements commenting on a trip and deleting a comment

### description of tasks to be completed
 - comment on a trip
 - delete a comment of a trip only performed by the owner of the comment
 - listing/ viewing all comments on a specific trip

### how should this Pull Request be tested?

 - checkout `feature/#181339541-trip-comments` branch
 - run in your terminal `docker-compose up` to start the docker containers and the project.
 - then run `docker exec -it cabal-backend sh` to inside the container
 - run `npx sequelize db:migrate ` and `npxsequelize db:seed:all` to migrate new tables in your database.

### pivotal tracker
 - [trip-comments](https://www.pivotaltracker.com/n/projects/2555280/stories/181339541)

### test in production
[swagger-Doc](https://staging-bare-feature-18-l5lzge.herokuapp.com/api-docs/)
N/A

2022-03-23 15:56 UTC, Tsa2341 requested changes
Also add the swagger or deployment link in your pull request

2022-03-23 15:56 UTC, Tsa2341 commented on src/controllers/trip.comments.controller.js
> +      return res.status(500).json({ message: 'internal server error' });
Let the developer know the error in all catch if unexpected

2022-03-23 15:56 UTC, Tsa2341 commented on src/controllers/trip.comments.controller.js
> +      return res.status(500).json({ message: 'internal server error' });
Let the developer know the error in all catch if unexpected

2022-03-23 15:56 UTC, Tsa2341 commented on src/controllers/trip.comments.controller.js
> +    }
Let the developer know the error in all catch if unexpected

please do so in all the other catches.

2022-03-24 07:03 UTC, Tsa2341 approved these changes

2022-03-24 08:24 UTC, blandri approved these changes

2022-03-24 13:50 UTC, niyonkurueric approved these changes

2022-03-24 14:31 UTC, Gabin-ishimwe approved these changes

2022-03-24 16:58 UTC, ncutixavier commented
### Comments

- Your PR has not been deployed
- Try to raise your test coverage to be above 85%

2022-03-29 08:56 UTC, ncutixavier commented
Squash your commit

2022-03-29 09:02 UTC, Code-250 commented
commits are squashed now

2022-03-29 12:39 UTC, ncutixavier requested changes

2022-03-29 12:39 UTC, ncutixavier commented on src/controllers/trip.comments.controller.js
> +        });
Change status code

2022-03-29 12:39 UTC, ncutixavier commented on src/controllers/trip.comments.controller.js
> +          .json({ message: 'you are not allowed to delete this comment' });
Change status code

2022-03-29 12:39 UTC, ncutixavier commented on tests/accommodation.test.js
> +      });
Refactor this code

2022-03-29 12:39 UTC, ncutixavier commented on tests/accommodation.test.js
> +        imagesId: ['456780rty']
Refactor this code

2022-03-29 12:39 UTC, ncutixavier commented on tests/user.test.js
> +    //   const { token } = res.body;
Remove commented code

2022-03-29 19:46 UTC, merged