#181339536 Reject/Approve Request (By Requester’s Manager)
atlp-rwanda/cabal-bn-be pull request #33
Opened 2022-03-23 21:15 UTC by niyonkurueric

### what does this Pull Request do?
this Pull Request implements how managers approve and reject the trip request
### description of tasks to be completed

- user should be able to send a request 
- the manager should be able to approve and reject requests of the user
- manager retrieves all Trip Request owner 
### how should this Pull Request be tested?

- locally: clone this repo and checkout **feature/#181339536-reject-approve-request**  branch
 - add all environment variables and run yarn run dev after running yarn run dbmigrate:all to seed data
 - checkout this api to login
 
            - **POST**  http://localhost:5000/api/v1/users/login

 - checkout this API to get all assigned users to the manager
 
             - **PUT**  http://localhost:5000/api/v1/users/assign-to-manager

- get the token and authenticate with a bearer and then hit these APIs to test the Approve and reject the trip request

           - **PATCH**  http://localhost:5000/api/v1/trips/{id}
### What are the relevant pivotal tracker stories?
[#181339536](https://www.pivotaltracker.com/story/show/181339536)
### Screenshots (if appropriate)
![Screenshot from 2022-03-23 23-13-40](https://user-images.githubusercontent.com/76616593/159796856-60383917-dfaa-461f-a275-71d4e02c00ee.png)

2022-03-28 09:08 UTC, Code-250 approved these changes
please fix your linter

2022-03-29 07:50 UTC, Gabin-ishimwe approved these changes

2022-03-29 12:55 UTC, ncutixavier requested changes

2022-03-29 12:55 UTC, ncutixavier commented on src/controllers/trip.controller.js
> +                });
Change status code

2022-03-29 12:55 UTC, ncutixavier commented on src/middlewares/role.middleware.js
> +export const checkRoleSame = async(req, res, next) => {
What about this middleware? Try to use meaningful name and make sure that you're returning appropriate status code

2022-03-29 12:55 UTC, ncutixavier commented on tests/password-reset.test.js
> +    // });
Remove commented code

2022-03-31 13:30 UTC, Tsa2341 approved these changes

2022-03-31 13:38 UTC, ncutixavier approved these changes

2022-03-31 13:38 UTC, merged