#181339531 user profile setting
atlp-rwanda/cabal-bn-be pull request #34
Opened 2022-03-24 06:39 UTC by Gabin-ishimwe

## What does this PR do?
create user profile
## Description of Task to be completed?
testing this feature in deployed environment
## How should this be manually tested?

## Any background context you want to provide?
to update a profile you need to first login and get you can be able to go and update the profile
## What are the relevant pivotal tracker stories?
[#181339531 ](https://www.pivotaltracker.com/n/projects/2555280/stories/181339531)
## Screenshots (if appropriate)
## Questions:

2022-03-24 11:41 UTC, Eli250 requested changes
It might not be safe to return user data on registration.
Just status, message, and the token are enough.

2022-03-24 11:41 UTC, Eli250 commented on src/controllers/user.controller.js
> +          data: getUser
Returning user data on registration is not necessary. Status and token and message are enough.

2022-03-24 11:41 UTC, Eli250 commented on src/controllers/user.controller.js
> +          data: finduserProfile
Consider not returning user data here. It might not be safe.

2022-03-24 11:41 UTC, Eli250 commented on src/validations/profile.validation.js
> +export default profileValidation
Add an empty line at the end.

2022-03-24 16:04 UTC, niyonkurueric approved these changes

2022-03-24 16:44 UTC, Code-250 approved these changes

2022-03-24 16:44 UTC, Code-250 commented on src/app.js
>  import cors from 'cors';
re un comment the express-form-data package

2022-03-29 12:56 UTC, ncutixavier commented
You need to increase test coverage

2022-03-31 09:11 UTC, Eli250 approved these changes

2022-03-31 09:38 UTC, ncutixavier approved these changes

2022-03-31 09:39 UTC, merged