#181339535: multi city trips
atlp-rwanda/cabal-bn-be pull request #36
Opened 2022-03-29 07:01 UTC by blandri

## What does this PR do?
Allows user to select multiple cities to travel to in one trip request

## Description of Task to be completed?

- Add arrival location as an array to the database
- Add options of inserting an object as a single city to travel to

## How should this be manually tested?
use this deployed link test the profile route, but first you need to register so that you can get a profile

swagger ...........

or
- clone this repo
- go to request trip
- enter a request with arrival location as an array of objects 

## What are the relevant pivotal tracker stories?

[#181339535](https://www.pivotaltracker.com/n/projects/2555280/stories/181339531)

## Screenshots (if appropriate)
<img width="1552" alt="image" src="https://user-images.githubusercontent.com/95901517/160551925-a9ff5dfd-85c7-4d5f-a821-28dc8edfeed5.png">
<img width="1552" alt="image" src="https://user-images.githubusercontent.com/95901517/160552050-30270e23-3c0c-4046-9e69-da0320f2d3e2.png">

2022-03-30 11:47 UTC, Eli250 requested changes
Resolve the conflicts and if there is something you can do to increase test coverages please do it.

2022-03-31 17:54 UTC, Code-250 approved these changes

2022-03-31 17:55 UTC, Tsa2341 approved these changes

2022-03-31 17:57 UTC, Eli250 approved these changes

2022-04-05 07:15 UTC, Code-250 approved these changes

2022-04-06 11:40 UTC, ncutixavier reviewed
- Change this error message 
![image](https://user-images.githubusercontent.com/51375428/161965977-e8a8dbe2-0c01-4ad1-bd5d-241994ddb30d.png)

- You need to check if user enter current year
![image](https://user-images.githubusercontent.com/51375428/161966837-77e4377a-68ce-46cb-ac1f-aa68a493eeff.png)

2022-04-06 19:01 UTC, Code-250 approved these changes

2022-04-06 19:05 UTC, merged