#181339469 setting-up-unit-tests
atlp-rwanda/cabal-bn-be pull request #4
Opened 2022-02-28 14:50 UTC by blandri

### What does this PR do?
Set up unit tests for the project

### Description of Task to be completed?
merge this PR so that other team member can start working on tests
### How should this be manually tested?

- Clone this repository and open the project in your code editor.
- to install all package on your local repo use: **yarn install** 
- to run the project use: **yarn run dev**

### What are the relevant pivotal tracker stories?
[#181339469](https://www.pivotaltracker.com/n/projects/2555280)
### Screenshots (if appropriate)
![image](https://user-images.githubusercontent.com/95901517/156003510-1e1e663e-2a27-419f-8a2d-72b06f77f4b1.png)

2022-02-28 16:20 UTC, Tsa2341 commented on .nyc_output/e0761902-7651-4daf-8e15-23c2f36343e5.json
> +{"C:\\Users\\landr\\Desktop\\cabal-bn-be\\src\\app.js":{"path":"C:\\Users\\landr\\Desktop\\cabal-bn-be\\src\\app.js","statementMap":{"0":{"start":{"line":3,"column":0},"end":{"line":5,"column":3}},"1
don't push .nyc files

2022-02-28 16:21 UTC, Tsa2341 commented on coverage/app.js.html
> +
I also, think coverage related files are not to be pushed

2022-02-28 17:35 UTC, Code-250 requested changes
work on all requested changes.

2022-02-28 17:35 UTC, Code-250 commented on .nyc_output/e0761902-7651-4daf-8e15-23c2f36343e5.json
> +{"C:\\Users\\landr\\Desktop\\cabal-bn-be\\src\\app.js":{"path":"C:\\Users\\landr\\Desktop\\cabal-bn-be\\src\\app.js","statementMap":{"0":{"start":{"line":3,"column":0},"end":{"line":5,"column":3}},"1
please do not push nyc_output folder

2022-02-28 17:35 UTC, Code-250 commented on coverage/app.js.html
> +            };
do not push coverage related folder

2022-03-01 09:22 UTC, Gabin-ishimwe requested changes
coverage folders are not needed in pushing

2022-03-01 13:50 UTC, niyonkurueric approved these changes

2022-03-01 14:28 UTC, Tsa2341 requested changes
please work on all comments.

if you go to your branch on Github you will see that the coverage and .nyc files are still in.
adding them in .gitignore will not delete them as it only prevents but does not delete already pushed code.

use [ this article ](https://dev.to/morinoko/useful-git-commands-for-removing-accidentally-pushed-or-committed-files-2ld) for reference on how to delete already pushed folder or file.

2022-03-02 06:13 UTC, Tsa2341 approved these changes

2022-03-02 18:31 UTC, Code-250 approved these changes

2022-03-02 18:50 UTC, Gabin-ishimwe approved these changes

2022-03-03 08:56 UTC, ncutixavier reviewed
Add Circle CI & Coveralls badges

2022-03-03 13:19 UTC, ncutixavier commented
@blandri  describe well how to test your code locally

2022-03-03 13:50 UTC, merged