Users should be able to mark all notifications as read
atlp-rwanda/cabal-bn-be pull request #40
Opened 2022-04-05 13:56 UTC by niyonkurueric

### what does this Pull Request do?
this Pull Request implements how Users should be able to mark all notifications as read
### description of tasks to be completed
- user should be able to view all notification
- the user should be able to read all notification 
- the user should mark all notifications as read 
### how should this Pull Request be tested?

- locally: clone this repo and checkout **feature/#181339546-mark-all-notifications**  branch
 - add all environment variables and run yarn run dev after running yarn run dbmigrate: all to seed data
 - checkout this API to login
 
            - **POST**  http://localhost:5000/api/v1/users/login
            - **POST**  http://localhost:5000/api/v1/notification/markall
      
### What are the relevant pivotal tracker stories?
[#181339546](https://www.pivotaltracker.com/story/show/181339546)
### Screenshots (if appropriate)
![Screenshot from 2022-04-05 15-54-41](https://user-images.githubusercontent.com/76616593/161769989-6c0507d4-061a-43b6-98d1-57b1cf351126.png)

2022-04-06 10:54 UTC, Eli250 requested changes
There are conflicts in your PR. Fix them first.

2022-04-19 05:56 UTC, Gabin-ishimwe approved these changes

2022-04-19 15:57 UTC, blandri approved these changes

2022-04-20 09:29 UTC, Code-250 approved these changes

2022-04-20 09:35 UTC, Eli250 approved these changes

2022-04-20 18:40 UTC, ncutixavier approved these changes

2022-04-20 18:41 UTC, merged