Feature/#181339545 notification updates
atlp-rwanda/cabal-bn-be pull request #43
Opened 2022-04-13 08:38 UTC by Gabin-ishimwe

2022-04-14 10:32 UTC, blandri approved these changes

2022-04-14 17:55 UTC, Tsa2341 approved these changes

2022-04-14 18:10 UTC, niyonkurueric approved these changes

2022-04-15 14:33 UTC, Code-250 requested changes
please work on all comments that I gave you and before pushing remove all unnecessary console logs.

2022-04-15 14:33 UTC, Code-250 commented on .env.sample
> +FROM_EMAIL=cabal2barefoot@gmail.com
please remove this email in your .env.sample

2022-04-15 14:33 UTC, Code-250 commented on src/app.js
> +// app.use(formData.union());
please do un comment these lines of code and also that line 10

2022-04-15 14:33 UTC, Code-250 commented on src/controllers/booking.controller.js
> +      const user = await new UserService().getUserId(req.user.id)
could you try to get user data from req.user instead of getting him from database since you are loggedIn unless you are getting onther user.

2022-04-15 14:33 UTC, Code-250 commented on src/controllers/booking.controller.js
> +          }
could you get this  link from dotenv

2022-04-15 14:33 UTC, Code-250 commented on src/controllers/trip.comments.controller.js
> +                if (recieveUser.in_app_notification == true) {
also here try to get user from req.user

2022-04-15 14:33 UTC, Code-250 commented on src/controllers/trip.controller.js
> +            const manager = await new UserService().getUserId(user.manager_id)
even here

2022-04-15 14:33 UTC, Code-250 commented on src/controllers/trip.controller.js
> +                }
please get routes from your environment variables

2022-04-15 14:33 UTC, Code-250 commented on src/database/models/notification.js
> +};
add an ending line at the end

2022-04-15 14:33 UTC, Code-250 commented on src/middlewares/booking.middleware.js
> +      //   return res.status(200).json({
delete all commented codes

2022-04-15 14:33 UTC, Code-250 commented on src/services/notification.service.js
> +}
add an ending line here

2022-04-15 14:33 UTC, Code-250 commented on src/services/trip.service.js
> +  //         'provider',
delete commented codes

2022-04-15 14:33 UTC, Code-250 commented on src/services/user.service.js
> +    //             model: Profile,
even these delete them

2022-04-15 14:33 UTC, Code-250 commented on tests/accommodation.test.js
> +  //         'In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying .',
before pushing please remove all commented codes

2022-04-15 14:33 UTC, Code-250 commented on tests/app.notification.test.js
> +    clientSocket = client.connect(`http://localhost:${port}`, {
could you try to get these url from your dotenv because what happens when we are going to connect to anothe url

2022-04-18 14:11 UTC, ncutixavier approved these changes

2022-04-18 14:12 UTC, merged