#181339470 Configure ESLint
atlp-rwanda/cabal-bn-be pull request #5
Opened 2022-02-28 14:53 UTC by niyonkurueric

### What does this PR do?
i checking for formating of ode
### Description of Task to be completed?
It'll help check for style violations and flag them
### How should this be manually tested?
- clone  my repository 
 - run in your terminal `yarn run dev` to start the project
### Any background context you want to provide?
### What are the relevant pivotal tracker stories?
 - [pivotal tracker link](https://www.pivotaltracker.com/n/projects/2555280)
### Screenshots
![Screenshot from 2022-02-28 16-51-51](https://user-images.githubusercontent.com/76616593/156004170-74e2e4cc-5062-486c-ad8b-f407e3d213d2.png)

### Questions:

2022-03-01 09:17 UTC, Gabin-ishimwe approved these changes

2022-03-02 16:48 UTC, tuyizerejean approved these changes

2022-03-03 13:20 UTC, ncutixavier requested changes

2022-03-03 13:20 UTC, ncutixavier commented on .eslintrc.json
> +  }
Add New Line

2022-03-03 13:20 UTC, ncutixavier commented on .hound.yml
> +enabled: false,
Add New Line

2022-03-03 13:20 UTC, ncutixavier commented on src/app.js
> +}
Add New Line

2022-03-04 11:43 UTC, closed without merging